### ISSUE TITLE
File inject stays in mode "sending files..." for ever 

### ISSUE THREAD

**Issue by MoYo2004** [node-red-contrib-utils/node-red-contrib-browser-utils#13]
after selecting a picture (jpeg) from the hard drive the node remains in status "sending files...."

**Comment by chughts** [comment]
Which version of the utils are you using? Current is 0.0.7. 

What is the size of the file that you are sending.
The sending status is set just before the upload is started, and should disappear when the file is received. Conceivably if the file is very short, then the file may be received before the node has had a chance to set the sending status, and hence sets the sending status after the file is received, but this occurrence should be rare.

For long files, then the status will disappear when the file is received. If it is not then the node-red server may have crashed due to memory limitations.

**Comment by MoYo2004** [comment]
Hi chughts,

thank you very much for your fast answer. Bu I found out, that the error is not your node, it is the receiving one (openVC) which for what ever reason does not receive files when you select car side detection.
Sorry for bothering.

Best regards
Michael
